server:
  port: 8081
  servlet:
    context-path: /phonebook
  
spring:
  application:
    name: phonebook

  datasource:
    driver-class-name: org.postgresql.Driver
    name: phonebook
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/phonebook
    hikari:
      schema: public
      auto-commit: true
      connection-init-sql: select 1
      connection-test-query: select 1
      pool-name: phonebook-pool
      maximum-pool-size: 5
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

logging:
  file:
    name: phonebook.log
  charset:
    console: UTF-8
  register-shutdown-hook: true
  level:
    root: info
    '[org.springframework.boot.jdbc]': debug
    '[com.zaxxer.hikari]' : debug  
    '[org.postgresql.jdbc]': debug
    '[org.springframework.jdbc]': debug